/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface InvalidComponent {}
  interface ValidComponent {}
}

declare namespace LocalJSX {
  interface InvalidComponent extends JSXBase.HTMLAttributes {}
  interface ValidComponent extends JSXBase.HTMLAttributes {}

  interface ElementInterfaces {
    'InvalidComponent': Components.InvalidComponent;
    'ValidComponent': Components.ValidComponent;
  }

  interface IntrinsicElements {
    'InvalidComponent': LocalJSX.InvalidComponent;
    'ValidComponent': LocalJSX.ValidComponent;
  }
}
export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface ElementInterfaces extends LocalJSX.ElementInterfaces {}
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}

declare global {


  interface HTMLInvalidComponentElement extends Components.InvalidComponent, HTMLStencilElement {}
  var HTMLInvalidComponentElement: {
    prototype: HTMLInvalidComponentElement;
    new (): HTMLInvalidComponentElement;
  };

  interface HTMLValidComponentElement extends Components.ValidComponent, HTMLStencilElement {}
  var HTMLValidComponentElement: {
    prototype: HTMLValidComponentElement;
    new (): HTMLValidComponentElement;
  };
  interface HTMLElementTagNameMap {
    'invalid-component': HTMLInvalidComponentElement
    'valid-component': HTMLValidComponentElement
  }

  interface ElementTagNameMap {
    'invalid-component': HTMLInvalidComponentElement;
    'valid-component': HTMLValidComponentElement;
  }
}

